### PR TITLE
Added packages to requirements

### PR DESCRIPTION
**Pull request by Ullarah**
Just had a go at installing and running locally, had to install these two extra python modules.

### CODE REVIEW

**Comment by BassThatHertz** [comment]
I don't think "confidential" should. As a quick double check, can you try uninstalling it and let me know if you run into any issues?

**Comment by retrodaredevil** [comment]
I can confirm that confidential is needed. I'm using Ubuntu 20.04.

**Comment by gurashish1singh** [comment]
Why can't we add 'youtube-dl' as well to the requirements.txt?

**Comment by retrodaredevil** [comment]
> Why can't we add 'youtube-dl' as well to the requirements.txt?

I believe that this repository contains part of the youtube-dl repository so that's not needed. I'm not really sure why part of youtube-dl is copy pasted directly, but I think that's the reason it's not needed in `requirements.txt`.

**Comment by BassThatHertz** [comment]
@gurashish1singh and @retrodaredevil I've actually removed `pip install youtube-dl` from the README now. My website uses the youtube_dl folder in this repository rather than the version of youtube-dl that you get with pip. The reason for this is explained below:

Recently, YouTube made a change which means that there is an issue when trying to embed the video thumbnail as cover art with youtube-dl. Someone has implemented [a fix](https://github.com/ytdl-org/youtube-dl/pull/25717) for this issue, but it has not been merged with the master branch of youtube-dl yet. Therefore, I cloned the youtube_dl folder in the [youtube-dl repository](https://github.com/ytdl-org/youtube-dl) and manually added the fix. So the youtube_dl folder that you see in my repository has this fix added.

On a side note, the thumbnail of the video only gets embedded as cover art if you use the "Audio [MP3]" button on my website.

**Pull request merged**
